webtalk_init -webtalk_dir C:/Users/Robby/Desktop/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/debouncer_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 10 01:21:41 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d552c134-884e-4d33-ac7f-a3345415adf0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "30fb60b44ebc411cbb373e79f92c4875" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 PRO 4750U with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1697 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2056 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6524_KB" -context "xsim\\usage"
webtalk_transmit -clientid 744614944 -regid "" -xml C:/Users/Robby/Desktop/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/debouncer_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Robby/Desktop/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/debouncer_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Robby/Desktop/Lab2/Lab2.sim/sim_1/behav/xsim/xsim.dir/debouncer_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
